name: build and publish release image

on:
  # On release events (also when a published release is converted from/to prerelease), push all patterns
  release:
    types: [released, prereleased]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ICR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push bee-ui local image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NEXT_PUBLIC_APP_NAME=Bee
            NEXT_PUBLIC_FEATURE_FLAGS={"Knowledge": false, "Files": true, "FunctionTools": true, "Observe": true}
            NEXT_PUBLIC_USERCONTENT_SITE_URL=http://bee-usercontent-site:5173
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-ui-local:latest
            ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-ui-local:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-ui-local:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-ui-local:buildcache,mode=max
